import { jsPDF } from 'jspdf';

export const generatePatientReport = (patient, encounters = []) => {
  const doc = new jsPDF();

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  let y = 25;

  // ================= HEADER =================
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 22, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('EHR MANAGEMENT SYSTEM', 15, 14);

  doc.setFontSize(9);
  doc.text(
    `Generated: ${new Date().toLocaleDateString()}`,
    pageWidth - 50,
    14
  );

  // ================= TITLE =================
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(20);
  doc.text('Patient Clinical Report', 15, y);

  y += 15;

  // ================= PATIENT CARD =================
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(15, y, 180, 42, 3, 3, 'F');

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Patient Information', 20, y + 8);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');

  doc.text(
    `Name: ${patient.firstName} ${patient.lastName}`,
    20,
    y + 18
  );

  doc.text(
    `Age: ${patient.age}`,
    120,
    y + 18
  );

  doc.text(
    `Gender: ${patient.gender}`,
    20,
    y + 28
  );

  doc.text(
    `Contact: ${patient.contactNumber}`,
    120,
    y + 28
  );

  doc.text(
    `Email: ${patient.email || 'N/A'}`,
    20,
    y + 38
  );

  y += 55;

  // ================= MEDICAL HISTORY =================
  doc.setTextColor(79, 70, 229);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Medical History', 15, y);

  y += 8;

  const history =
    patient.medicalHistory || 'No medical history available';

  const historyLines = doc.splitTextToSize(history, 165);

  const historyHeight =
    Math.max(18, historyLines.length * 6 + 8);

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(
    15,
    y - 5,
    180,
    historyHeight,
    2,
    2,
    'F'
  );

  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);

  doc.text(historyLines, 20, y + 3);

  y += historyHeight + 12;

  // ================= ENCOUNTERS =================
  doc.setTextColor(79, 70, 229);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Clinical Encounters', 15, y);

  y += 10;

  if (encounters.length === 0) {
    doc.setTextColor(120);
    doc.text('No encounters found.', 15, y);
  } else {
    encounters.forEach((encounter, index) => {
      const symptoms = encounter.symptoms || 'N/A';
      const diagnosis = encounter.diagnosis || 'N/A';
      const notes = encounter.notes || 'No notes available';

      const notesLines = doc.splitTextToSize(notes, 150);

      const cardHeight =
        45 + notesLines.length * 5;

      if (y + cardHeight > 260) {
        doc.addPage();
        y = 20;
      }

      doc.setFillColor(248, 250, 252);
      doc.roundedRect(
        15,
        y,
        180,
        cardHeight,
        2,
        2,
        'F'
      );

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(12);

      doc.text(
        `Encounter #${index + 1}`,
        20,
        y + 8
      );

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);

      doc.text(
        `Date: ${new Date(
          encounter.date
        ).toLocaleDateString()}`,
        20,
        y + 16
      );

      doc.setFont('helvetica', 'bold');
      doc.text('Symptoms:', 20, y + 24);

      doc.setFont('helvetica', 'normal');
      doc.text(symptoms, 50, y + 24);

      doc.setFont('helvetica', 'bold');
      doc.text('Diagnosis:', 20, y + 32);

      doc.setFont('helvetica', 'normal');
      doc.text(diagnosis, 50, y + 32);

      doc.setFont('helvetica', 'bold');
      doc.text('Notes:', 20, y + 40);

      doc.setFont('helvetica', 'normal');
      doc.text(notesLines, 50, y + 40);

      y += cardHeight + 10;
    });
  }

  // ================= FOOTER =================
  const totalPages =
    doc.internal.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    doc.setDrawColor(220);
    doc.line(
      15,
      pageHeight - 15,
      pageWidth - 15,
      pageHeight - 15
    );

    doc.setFontSize(9);
    doc.setTextColor(120);

    doc.text(
      'Generated by EHR Clinical Portal',
      15,
      pageHeight - 8
    );

    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - 35,
      pageHeight - 8
    );
  }

  doc.save(
    `Patient_Report_${patient.firstName}_${patient.lastName}.pdf`
  );
};



